modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "create_deepslate_processing"
version = "${version}"
displayName = "Create: Deepslate Processing"
authors = "create_deepslate_processing"
description = '''
Adds processing for deepslate into useful minerals
'''
logoFile = "icon.png"

[[dependencies.create_deepslate_processing]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_deepslate_processing]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_deepslate_processing]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"